<a href="https://colab.research.google.com/github/Ashwitha2305/ADM/blob/main/ADM_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd

In [38]:
df=pd.read_csv("/content/customer_sales_data.csv")

In [56]:
df.dtypes

Sales_ID              int64
Product_Category     object
Region               object
Sales_Amount        float64
Quantity_Sold         int64
Sales_Date           object
Customer_Age          int64
Customer_Gender       int64
Sales_Profit        float64
dtype: object

In [57]:
df

,Sales_ID,Product_Category,Region,Sales_Amount,Quantity_Sold,Sales_Date,Customer_Age,Customer_Gender,Sales_Profit
0,1,Home Appliances,South,654.82,5,2023-03-25,44,2,163.7050
1,2,Home Appliances,East,624.38,5,2023-03-24,37,2,156.0950
2,3,Electronics,West,427.01,6,2023-03-11,53,2,106.7525
3,4,Clothing,East,658.72,4,2023-03-19,42,1,164.6800
4,5,Clothing,North,272.72,8,2023-03-23,42,2,68.1800
...,...,...,...,...,...,...,...,...,...
95,96,Home Appliances,West,213.80,4,2023-03-10,48,1,53.4500
96,97,Clothing,West,373.18,5,2023-03-25,42,2,93.2950
97,98,Electronics,South,610.88,3,2023-03-28,34,1,152.7200
98,99,Home Appliances,West,661.88,9,2023-03-30,24,1,165.4700
99,100,Clothing,North,584.18,5,2023-03-15,50,1,146.0450

In [40]:
df.isnull()

,Sales_ID,Product_Category,Region,Sales_Amount,Quantity_Sold,Sales_Date,Customer_Age,Customer_Gender
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False

In [41]:
df_encoded = pd.get_dummies(df, columns=['Product_Category', 'Region'], drop_first=True)

In [42]:
df_encoded

,Sales_ID,Sales_Amount,Quantity_Sold,Sales_Date,Customer_Age,Customer_Gender,Product_Category_Electronics,Product_Category_Home Appliances,Region_North,Region_South,Region_West
0,1,654.82,5,2023-03-25,44,Female,False,True,False,True,False
1,2,624.38,5,2023-03-24,37,Female,False,True,False,False,False
2,3,427.01,6,2023-03-11,53,Female,True,False,False,False,True
3,4,658.72,4,2023-03-19,42,Male,False,False,False,False,False
4,5,272.72,8,2023-03-23,42,Female,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
95,96,213.80,4,2023-03-10,48,Male,False,True,False,False,True
96,97,373.18,5,2023-03-25,42,Female,False,False,False,False,True
97,98,610.88,3,2023-03-28,34,Male,True,False,False,True,False
98,99,661.88,9,2023-03-30,24,Male,False,True,False,False,True
99,100,584.18,5,2023-03-15,50,Male,False,False,True,False,False

In [43]:
from sklearn.preprocessing import LabelEncoder

In [45]:
df["Customer_Gender"] = df["Customer_Gender"].map({"Male": 1, "Female": 2})
print(df)

    Sales_ID Product_Category Region  Sales_Amount  Quantity_Sold  Sales_Date  \
0          1  Home Appliances  South        654.82              5  2023-03-25
1          2  Home Appliances   East        624.38              5  2023-03-24
2          3      Electronics   West        427.01              6  2023-03-11
3          4         Clothing   East        658.72              4  2023-03-19
4          5         Clothing  North        272.72              8  2023-03-23
..       ...              ...    ...           ...            ...         ...
95        96  Home Appliances   West        213.80              4  2023-03-10
96        97         Clothing   West        373.18              5  2023-03-25
97        98      Electronics  South        610.88              3  2023-03-28
98        99  Home Appliances   West        661.88              9  2023-03-30
99       100         Clothing  North        584.18              5  2023-03-15

    Customer_Age  Customer_Gender
0             44                2
1             37                2
2             53                2
3             42                1
4             42                2
..           ...              ...
95            48                1
96            42                2
97            34                1
98            24                1
99            50                1

[100 rows x 8 columns]

In [47]:
df['Sales_Profit'] = df['Sales_Amount'] * 0.25
print(df)

    Sales_ID Product_Category Region  Sales_Amount  Quantity_Sold  Sales_Date  \
0          1  Home Appliances  South        654.82              5  2023-03-25
1          2  Home Appliances   East        624.38              5  2023-03-24
2          3      Electronics   West        427.01              6  2023-03-11
3          4         Clothing   East        658.72              4  2023-03-19
4          5         Clothing  North        272.72              8  2023-03-23
..       ...              ...    ...           ...            ...         ...
95        96  Home Appliances   West        213.80              4  2023-03-10
96        97         Clothing   West        373.18              5  2023-03-25
97        98      Electronics  South        610.88              3  2023-03-28
98        99  Home Appliances   West        661.88              9  2023-03-30
99       100         Clothing  North        584.18              5  2023-03-15

    Customer_Age  Customer_Gender  Sales_Profit
0             44                2      163.7050
1             37                2      156.0950
2             53                2      106.7525
3             42                1      164.6800
4             42                2       68.1800
..           ...              ...           ...
95            48                1       53.4500
96            42                2       93.2950
97            34                1      152.7200
98            24                1      165.4700
99            50                1      146.0450

[100 rows x 9 columns]

In [58]:
sales_summary = df.groupby('Product_Category').agg({'Sales_Amount': 'sum', 'Sales_Profit': 'mean'})
print(sales_summary)

                  Sales_Amount  Sales_Profit
Product_Category
Clothing              14830.58    102.990139
Electronics            8404.22    100.050238
Home Appliances       17699.09    102.901686

In [54]:
sales_pivot = pd.pivot_table(df, values='Sales_Amount', index='Region', columns='Product_Category', aggfunc='sum')
print(sales_pivot)

Product_Category  Clothing  Electronics  Home Appliances
Region
East               3372.53      1403.38          6648.96
North              3196.94      1334.80          6842.64
South              5225.84      2660.56          1825.88
West               3035.27      3005.48          2381.61